"""Verifier agent for completeness checks, confidence scoring, and final output formatting."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from llm.client import cost_tracker, llm_client


class VerifierAgent:
    """Verify execution integrity and produce clean, structured final outputs."""

    def verify(self, plan: dict[str, Any], execution_results: dict[str, Any]) -> dict[str, Any]:
        """Perform end-to-end verification, confidence scoring, and formatting.

        Args:
            plan: Original plan generated by the planner.
            execution_results: Structured output from executor.

        Returns:
            Final validated response dictionary with metadata.
        """
        print("🔍 Verifying results...")
        try:
            is_complete, missing_steps = self._check_completeness(plan, execution_results)
            formatted = self._format_with_llm(plan, execution_results)

            confidence = self._calculate_confidence(plan, execution_results, formatted)
            formatted["confidence_score"] = confidence.get("confidence_score", 0)
            formatted["confidence_grade"] = confidence.get("confidence_grade", "F")
            formatted["confidence_reason"] = confidence.get("confidence_reason", "No confidence reason available")
            formatted["result_strengths"] = confidence.get("strengths", [])
            formatted["result_deductions"] = confidence.get("deductions", [])

            validated = self._validate_output(formatted)
            validated["is_complete"] = is_complete
            validated["missing_steps"] = missing_steps

            print("✅ Verification complete")
            return validated
        except Exception as exc:
            fallback = {
                "verified": False,
                "summary": "Verification encountered an internal error",
                "data_sources": [],
                "error": str(exc),
                "confidence_score": 0,
                "confidence_grade": "F",
                "confidence_reason": "Verification failed before confidence scoring",
                "result_strengths": [],
                "result_deductions": [str(exc)],
            }
            print(f"⚠️ Verification failed: {exc}")
            print("✅ Verification complete")
            return self._validate_output(fallback)

    def _check_completeness(self, plan: dict[str, Any], results: dict[str, Any]) -> tuple[bool, list[int]]:
        """Check whether every planned step has a successful execution result."""
        planned_steps = plan.get("steps", []) if isinstance(plan, dict) else []
        result_items = results.get("results", []) if isinstance(results, dict) else []

        expected_step_numbers = [int(step.get("step")) for step in planned_steps if "step" in step]
        successful_step_numbers = {
            int(item.get("step"))
            for item in result_items
            if item.get("success") is True and item.get("step") is not None
        }

        missing_or_failed = [n for n in expected_step_numbers if n not in successful_step_numbers]
        is_complete = len(missing_or_failed) == 0

        if not is_complete:
            print(f"⚠️ Incomplete verification. Failed/missing steps: {missing_or_failed}")

        return is_complete, missing_or_failed

    def _format_with_llm(self, plan: dict[str, Any], results: dict[str, Any]) -> dict[str, Any]:
        """Use the LLM to merge raw multi-tool outputs into a clean JSON object."""
        system_prompt = """
      You are a verification and formatting agent.
      You receive raw API results from multiple tools and must format them
      into a clean, structured JSON response for the user.

      Rules:
      - Combine all results into one cohesive JSON object
      - Use clear, descriptive key names (snake_case)
      - Remove any null, empty, or redundant fields
      - Add a "summary" field: a 2-3 sentence human-readable summary
        of all the findings
      - Add "verified": true at the top level
      - Add "data_sources": list of tools that were actually called
      - Preserve all important data — do not summarize away details
      - Respond ONLY with valid JSON, no explanation
      """

        payload = {"plan": plan, "results": results}
        user_message = json.dumps(payload, ensure_ascii=False, default=str)

        try:
            response = llm_client.chat(system_prompt, user_message, expect_json=True)
            cost_tracker.log("VerifierAgent", user_message, response)
            parsed = self._safe_parse_json(response)
            if isinstance(parsed, dict):
                return parsed
            return {
                "verified": False,
                "summary": "Task completed but formatting encountered an issue.",
                "data_sources": [],
                "raw_results": results.get("results", []),
            }
        except Exception as exc:
            print(f"⚠️ Verifier formatting failed: {exc}")
            raw_results = results.get("results", []) if isinstance(results, dict) else []
            return {
                "verified": False,
                "error": "Formatting failed",
                "raw_results": raw_results,
                "summary": "Verification formatting encountered an error",
            }

    def _safe_parse_json(self, text: str) -> dict[str, Any] | None:
        """Try multiple strategies to parse JSON from LLM response."""
        # Strategy 1: direct parse
        try:
            parsed = json.loads(text)
            return parsed if isinstance(parsed, dict) else None
        except Exception:
            pass

        # Strategy 2: extract from markdown code block
        import re

        patterns = [
            r"```json\s*(.*?)\s*```",
            r"```\s*(.*?)\s*```",
            r"\{.*\}",
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.DOTALL)
            if match:
                try:
                    candidate = match.group(1) if "```" in pattern else match.group(0)
                    parsed = json.loads(candidate)
                    return parsed if isinstance(parsed, dict) else None
                except Exception:
                    continue

        return None

    def _calculate_confidence(
        self,
        plan: dict[str, Any],
        results: dict[str, Any],
        formatted_output: dict[str, Any],
    ) -> dict[str, Any]:
        """Calculate confidence score and quality signals for result output.

        Args:
            plan: Plan dictionary produced by planner.
            results: Executor output dictionary.
            formatted_output: Formatted verifier output prior to validation.

        Returns:
            Confidence dictionary with score, grade, reason, and diagnostics.
        """
        default_confidence = {
            "confidence_score": 0,
            "confidence_grade": "F",
            "confidence_reason": "Unable to assess confidence",
            "deductions": ["Confidence scoring failed"],
            "strengths": [],
        }

        system_prompt = """
      You are a quality assessment agent.
      Evaluate the quality and completeness of API results
      and return a confidence score.
      
      Scoring criteria:
      - All planned steps completed successfully: +40 points
      - No errors in any step: +20 points  
      - All expected fields present in results: +20 points
      - Data is recent and non-empty: +10 points
      - No self-healing was needed: +10 points
      
      Return ONLY this JSON:
      {
        "confidence_score": 0-100,
        "confidence_grade": "A/B/C/D/F",
        "confidence_reason": "one sentence explanation",
        "deductions": ["list of reasons for any point deductions"],
        "strengths": ["list of what went well"]
      }
      """

        payload = {
            "plan_steps": len(plan.get("steps", [])) if isinstance(plan, dict) else 0,
            "steps_executed": results.get("steps_executed", 0) if isinstance(results, dict) else 0,
            "errors": results.get("errors", []) if isinstance(results, dict) else [],
            "self_healed_count": results.get("self_healed_count", 0) if isinstance(results, dict) else 0,
            "cache_hits": results.get("cache_hits", 0) if isinstance(results, dict) else 0,
            "output_keys": list(formatted_output.keys()) if isinstance(formatted_output, dict) else [],
        }

        try:
            user_message = json.dumps(payload, ensure_ascii=False, default=str)
            response = llm_client.chat(system_prompt, user_message, expect_json=True)
            cost_tracker.log("VerifierAgent", user_message, response)
            parsed = json.loads(response)
            if not isinstance(parsed, dict):
                raise ValueError("Confidence response is not a JSON object")

            score = parsed.get("confidence_score", 0)
            try:
                score_int = int(score)
            except Exception:
                score_int = 0
            score_int = max(0, min(100, score_int))

            grade = str(parsed.get("confidence_grade", "")).strip().upper() or self._grade_from_score(score_int)
            reason = str(parsed.get("confidence_reason", "")).strip() or "Confidence assessed"
            deductions = parsed.get("deductions", [])
            strengths = parsed.get("strengths", [])

            if not isinstance(deductions, list):
                deductions = []
            if not isinstance(strengths, list):
                strengths = []

            color = "bright_red"
            if score_int >= 80:
                color = "bright_green"
            elif score_int >= 60:
                color = "bright_yellow"

            print(f"📊 [{color}]Confidence: {score_int}/100 ({grade}) — {reason}[/{color}]")

            return {
                "confidence_score": score_int,
                "confidence_grade": grade,
                "confidence_reason": reason,
                "deductions": deductions,
                "strengths": strengths,
            }
        except Exception as exc:
            print(f"📊 [bright_red]Confidence: 0/100 (F) — Confidence scoring failed ({exc})[/bright_red]")
            return default_confidence

    def _validate_output(self, output: dict[str, Any]) -> dict[str, Any]:
        """Ensure required keys exist and attach verification metadata."""
        output.setdefault("verified", False)
        output.setdefault("summary", "No summary available")
        output.setdefault("data_sources", [])

        output["agent_version"] = "1.0.0"
        output["timestamp"] = datetime.now().isoformat()
        return output

    @staticmethod
    def _grade_from_score(score: int) -> str:
        """Map numeric confidence score to letter grade."""
        if score >= 90:
            return "A"
        if score >= 80:
            return "B"
        if score >= 70:
            return "C"
        if score >= 60:
            return "D"
        return "F"


verifier_agent = VerifierAgent()


if __name__ == "__main__":
    """Run a simple verifier self-test with mock execution data."""
    sample_plan = {
        "task_summary": "Get weather and tech news",
        "steps": [
            {
                "step": 1,
                "tool": "WeatherTool",
                "action": "get_current_weather",
                "params": {"city": "San Francisco"},
                "description": "Get current weather",
            },
            {
                "step": 2,
                "tool": "NewsTool",
                "action": "get_top_headlines",
                "params": {"category": "technology", "country": "us", "limit": 2},
                "description": "Get top tech headlines",
            },
        ],
    }
    sample_results = {
        "task_summary": "Get weather and tech news",
        "steps_executed": 2,
        "steps_total": 2,
        "results": [
            {
                "step": 1,
                "tool": "WeatherTool",
                "action": "get_current_weather",
                "description": "Get current weather",
                "result": {"city": "San Francisco", "temperature_c": 18.2},
                "from_cache": False,
                "success": True,
                "error": None,
                "self_healed": False,
            },
            {
                "step": 2,
                "tool": "NewsTool",
                "action": "get_top_headlines",
                "description": "Get top tech headlines",
                "result": [{"title": "Example headline", "source": "Demo Source"}],
                "from_cache": False,
                "success": True,
                "error": None,
                "self_healed": False,
            },
        ],
        "errors": [],
        "cache_hits": 0,
        "self_healed_count": 0,
        "execution_time_seconds": 0.21,
    }

    verified = verifier_agent.verify(sample_plan, sample_results)
    print(json.dumps(verified, indent=2, ensure_ascii=False))
